language: cpp
sudo: required
dist: trusty
env:
#  - BUILD_TYPE=gpu
#  - BUILD_TYPE=cpu
  - BUILD_TYPE=training

compiler:
  - gcc

addons:
  apt:
    packages:
      libboost-all-dev
      libopenblas-dev
      opencl-headers
      ocl-icd-libopencl1
      ocl-icd-opencl-dev
      zlib1g-dev
      clinfo
      python3-dev
      python3-pip

install:
  - clinfo
  - sudo pip3 install --upgrade pip
  - pip3 install tensorflow
  - python3 -V
  - pip3 -V

script:
  - if [$BUILD_TYPE == gpu]; then cmake --build . --target lczero --config Release -- -j2; fi
  - if [$BUILD_TYPE == cpu]; then cmake --build . --config Release -- -j2; fi
  - if [$BUILD_TYPE == cpu]; then ./tests; fi
  - if [$BUILD_TYPE == training]; then python3 training/tf/chunkparser.py; python3 training/tf/shufflebuffer.py; fi
